version: '3.7'
services:
  geth:
    image: trufflesuite/ganache-cli
    ports:
      - 8545:8545
    command:
      - ganache-cli
      - "-l 8000000"
      - "-g 1000000000"
      - --account
      - "0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501200,1000000000000000000000000"
      - --account
      - "0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501201,1000000000000000000000000"
      - --account
      - "0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501202,1000000000000000000000000"
      - --account
      - "0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501203,1000000000000000000000000"
      - --account
      - "0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501204,1000000000000000000000000"
      - --account
      - "0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501205,1000000000000000000000000"
      - --account
      - "0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501206,1000000000000000000000000"
      - --account
      - "0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501207,1000000000000000000000000"
      - --account
      - "0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501208,1000000000000000000000000"
      - --account
      - "0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501209,1000000000000000000000000"

  nodedb:
    image: postgres
    ports:
      - 54321:54322
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=bitclave
      - POSTGRES_USER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 27017:27017
    logging:
      driver: none

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: elasticsearch
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  base-node:
    image: base/node
    ports:
      - 8080:8080
    depends_on:
      - nodedb
      - geth
    environment:
      - PROFILE=docker
      - PORT=8080
      - RT_SEARCH_URL=http://rt-search:5001/
      - JDBC_DATABASE_URL=jdbc:postgresql://nodedb:5432/postgres
      - JDBC_DATABASE_USERNAME=postgres
      - JDBC_DATABASE_PASSWORD=bitclave
      - ETHEREUM_RPC_URL=http://geth:8545/
      - OWNER_PRIVATE_KEY=0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501200
      - DNS_CONTRACT_ADDRESS=0x0f5ea0a652e851678ebf77b69484bfcd31f9459b
      - ETHEREUM_GAS_PRICE=8000000
      - ETHEREUM_GAS_LIMIT=8000000

  matcher:
    image: base/matcher
    depends_on:
      - base-node
    restart: on-failure
    environment:
      - BASE_NODE_URL=http://base-node:8080/

  rt-search:
    image: base/rt-search
    ports:
      - 5001:5001
    depends_on:
      - base-node
      - elasticsearch
    restart: on-failure
    environment:
      - PROFILE=docker
      - PORT=5001
      - NODE_END_POINT=http://base-node:8080/
      - ELASTIC_CLUSTER_NAME=docker-cluster
      - ELASTIC_HOST=elasticsearch
      - ELASTIC_PORT=9300
      - ELASTIC_OFFER_INDEX_NAME=docker-offer

  auth-frontend:
    image: base/auth-frontend
    restart: on-failure
    depends_on:
      - base-node
    ports:
      - 5002:4200
    environment:
      - PRODUCTION=false
      - BASE_NODE_API_URL=http://base-node:8080/
      - AUTH_VIA_EMAIL=false
      - KEYCLOACK_CONFIG_URL=https://baseauth.bitclave.com:8443/auth
      - KEYCLOACK_CONFIG_REALM=BASE
      - KEYCLOACK_CONFIG_CLIENT_ID=base-auth
      - KEYCLOACK_LOGGED_IN_URL=http://auth-frontend:5002/auth/loggedin
      - KEYCLOACK_LOGGED_OUT_URL=http://auth-frontend:5002/auth/logout/close
      - KEYCLOACK_LOGOUT_URL=http://auth-frontend:5002/auth/logout
      - LOGGER_URL=https://shepherd-backend-staging2.herokuapp.com/log
      - LOGGER_LEVEL=debug
      - LOGGER_APP=base-auth-frontend
      - IS_BOTH_LOGIN_OPTIONS_SHOW=true
      - FB_REDIRECT_URL=https://shepherd-staging.herokuapp.com/cabinet/dashboard/

  auth-sdk:
    image: base/auth-sdk
    restart: on-failure
    ports:
      - 5003:5003
      - 5004:5004
    environment:
      - WIDGET_URL=http://auth-frontend:5002/
      - WIDGET_LOCATION=auth/widget

  shepherd-backend:
    image: base/shepherd-backend
    restart: on-failure
    depends_on:
      - auth-sdk
      - mongodb
      - elasticsearch
    ports:
      - 5005:5005
    environment:
      - NODE_ENV=docker
      - PORT=5005
      - PASS=7d188f87-c5a0-4961-af27-c5fa40b81f8a
      - SITE_ORIGIN=localhost
      - UNIQUE_PHRASE=unique message for sig
      - ELASTIC_HOST=http://elasticsearch:9200
      - ELASTIC_ENABLE=true
      - ELASTIC_INDEX=bitclave-docker-log
      - ELASTIC_TYPE=bitclave-docker-log
      - MONGODB_URI=mongodb://mongodb:27017/bitclave
      - BASE_PUBLIC_KEY=0388308aa01dfea2289332b5b260867ff869fa571a6de290033c09a536c529cf46
      - BASE_NODE_URL=http://base-node:8080/

volumes:
  postgres_data: {}
  esdata:
    driver: local
