version: '3.7'
services:
    base-node:
        image: base/node
        container_name: base-node
        ports:
          - 8080:8080
        restart: on-failure
        environment:
          - PROFILE=docker
          - PORT=8080
          - RT_SEARCH_URL=http://rt-search:5001/
          - JDBC_DATABASE_URL=jdbc:postgresql://nodedb:5432/docker
          - JDBC_DATABASE_USERNAME=docker
          - JDBC_DATABASE_PASSWORD=bitclave
          - ETHEREUM_RPC_URL=http://geth:8545/
          - OWNER_PRIVATE_KEY=0x2bdd21761a483f71054e14f5b827213567971c676928d9a1808cbfa4b7501200
          - DNS_CONTRACT_ADDRESS=0x0f5ea0a652e851678ebf77b69484bfcd31f9459b
          - ETHEREUM_GAS_PRICE=8000000
          - ETHEREUM_GAS_LIMIT=8000000
          - JAVA_OPTS=-Xms128m -Xmx128m

networks:
  default:
    name: bitclave
